(feature) Add Stage Manager (com.apple.WindowManager) settings
LnL7/nix-darwin pull request #1002
Opened 2024-07-11 13:00 UTC by malko42

All credits go to @AlexOwl. Their [PR](https://github.com/LnL7/nix-darwin/pull/505) looked abandonned so I reported their changes and addressed the change requests.

2024-07-11 16:25 UTC, Samasaur1 approved these changes
Assuming that you've tested it and that those are still the correct defaults keys to use for those settings, this looks good to me

2024-07-11 17:52 UTC, malko42 commented
Hi @Samasaur1 and thanks for the review!
If you compare this PR with the orginal one the options are not the same. I added and tested only the options that I was interested in. I'm not sure about the default values though I took my own system as reference since I haven't touched those options AFAIK but still not 100% sure.
Is there an up-to-date list somewhere listing all `com.apple.*` settings ?

Also there are a few commonly defined options in [Nix config files](https://github.com/ryan4yin/nix-config/blob/1d66cf655daab10d1cef80897d7521046e5f8241/modules/darwin/system.nix#L126) do you want me to add them in a later PR or on this one ?

2024-07-11 18:36 UTC, Samasaur1 commented
> Hi @Samasaur1 and thanks for the review!
> 
> If you compare this PR with the orginal one the options are not the same. I added and tested only the options that I was interested in. I'm not sure about the default values though I took my own system as reference since I haven't touched those options AFAIK but still not 100% sure.

I think you're right about the default values. I also don't think it _really_ matters all too much because I think if people are looking at these options, they're probably planning to set them anyway.

I did look again at your `EnableStandardClickToShowDesktop` option, and I think you should update the docs you wrote for it to say that `false` means "Only in Stage Manager" and `true` means Always

> Is there an up-to-date list somewhere listing all `com.apple.*` settings ?

Wouldn't that be nice! I wish. I know there's <https://macos-defaults.com/> and maybe other sites like it, but I don't think they're comprehensive

> Also there are a few commonly defined options in [Nix config files](https://github.com/ryan4yin/nix-config/blob/1d66cf655daab10d1cef80897d7521046e5f8241/modules/darwin/system.nix#L126) do you want me to add them in a later PR or on this one ?

I'd say you should feel free to add any options under `com.apple.WindowManager` in this PR, but other defaults options should have their own PRs

2024-07-20 08:15 UTC, Enzime requested changes
Can you rebase your branch on top of master and squash all your commits into a singular one?

2024-07-20 08:15 UTC, Enzime commented on modules/system/defaults/WindowManager.nix
> +        Apple menu > System Settings > Dekstop and Dock > Desktop and Stage Manager
```suggestion
```

2024-07-20 08:15 UTC, Enzime commented on modules/system/defaults/WindowManager.nix
> +        Apple menu > System Settings > Dekstop and Dock > Desktop and Stage Manager
```suggestion
```

2024-07-21 11:29 UTC, malko42 commented
Few things to note:
- I added all the options I could effectively test
- I named the options after the ones from Apple but I'm not happy with it. I find them at best non explicit and most of the time logically opposite of their UI counterpart

2024-07-22 01:50 UTC, Enzime requested changes
Can you update the tests?

https://github.com/LnL7/nix-darwin/blob/master/tests/fixtures/system-defaults-write/activate-user.txt
https://github.com/LnL7/nix-darwin/blob/master/tests/system-defaults-write.nix

2024-07-22 01:50 UTC, Enzime commented on modules/system/defaults-write.nix
> +        ${concatStringsSep "\n" WindowManager}
```suggestion
        ${concatStringsSep "\n" WindowManager}

```

2024-08-02 11:42 UTC, malko42 commented
> Can you update the tests?
> 
> https://github.com/LnL7/nix-darwin/blob/master/tests/fixtures/system-defaults-write/activate-user.txt https://github.com/LnL7/nix-darwin/blob/master/tests/system-defaults-write.nix

Done

2024-08-02 14:34 UTC, Enzime approved these changes
LGTM

Thanks for the contribution

2024-08-02 14:34 UTC, merged