feat: add netdata service
LnL7/nix-darwin pull request #1077
Opened 2024-09-16 05:36 UTC by rsrohitsingh682

resolves #769

2024-09-16 14:57 UTC, srid commented
Would require https://github.com/NixOS/nixpkgs/pull/341472 I suppose?

2024-09-17 20:31 UTC, srid approved these changes
I tested this to work on a Mac. 

But note that cloud support is disabled in nixpkgs:

<img width="253" alt="image" src="https://github.com/user-attachments/assets/52151543-a933-45b1-8b17-b19707c38a7f">

https://github.com/khaneliman/nixpkgs/blob/418918ebb1024b8cb401d7386fcc99fc8d77ac1e/pkgs/top-level/all-packages.nix#L9671

Someone should open an issue for this; and ideally fix it.

2024-09-18 04:16 UTC, rsrohitsingh682 commented
> I tested this to work on a Mac.
> 
> But note that cloud support is disabled in nixpkgs:
> 
> <img alt="image" width="253" src="https://private-user-images.githubusercontent.com/3998/368331175-52151543-a933-45b1-8b17-b19707c38a7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2Mjg0MzgsIm5iZiI6MTcyNjYyODEzOCwicGF0aCI6Ii8zOTk4LzM2ODMzMTE3NS01MjE1MTU0My1hOTMzLTQ1YjEtOGIxNy1iMTk3MDdjMzhhN2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMDI1NTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzUxYTEwZGFkNTMzZmVhNzJhNWVmYjA3MTkyNjI5ZTkxOGYxYzNkOWQ3NDExNTBhMTc3ZGZjYmE2MGJkNDM3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qk1j2hIT_v8TL2YHgUuwOXnhQN4jrA34vC1CNjwYbyQ">
> https://github.com/khaneliman/nixpkgs/blob/418918ebb1024b8cb401d7386fcc99fc8d77ac1e/pkgs/top-level/all-packages.nix#L9671
> 
> Someone should open an issue for this; and ideally fix it.

https://github.com/NixOS/nixpkgs/pull/342708

2024-09-18 14:45 UTC, srid commented
> NixOS/nixpkgs#342708

Tested it to work on aarch64-darwin.

2024-09-23 18:19 UTC, rsrohitsingh682 commented
Requesting review from [nix-darwin](https://github.com/LnL7/nix-darwin) maintainers on this PR.

@Enzime @emilazy @antoineco

2024-09-23 18:43 UTC, antoineco commented
(just to clarify, I'm not a project maintainer!)

2024-09-23 18:52 UTC, rsrohitsingh682 commented
> (just to clarify, I'm not a project maintainer!

Apologies for misidentification. Thank you for correcting me.

2024-09-30 06:21 UTC, rsrohitsingh682 commented
Requesting review from ([nix-darwin](https://github.com/LnL7/nix-darwin)) maintainers again.

@emilazy @Enzime

2024-10-01 06:55 UTC, Enzime requested changes

2024-10-01 06:55 UTC, Enzime commented on modules/services/monitoring/netdata.nix
> +  meta.maintainers = [ "rsrohitsingh682" ];
```suggestion
  meta.maintainers = [ lib.maintainers.rsrohitsingh682 or "rsrohitsingh682" ];
```

2024-10-01 06:55 UTC, Enzime commented on modules/services/monitoring/netdata.nix
> +      };
```suggestion
      enable = mkEnableOption "Netdata daemon";
```

2024-10-01 06:55 UTC, Enzime commented on modules/services/monitoring/netdata.nix
> +      };
```suggestion
      package = lib.mkPackageOption pkgs "netdata" {};
```

2024-10-01 06:55 UTC, Enzime commented on modules/services/monitoring/netdata.nix
> +        ];
```suggestion
        command = lib.getExe cfg.package;
```

2024-10-01 06:55 UTC, Enzime commented on modules/services/monitoring/netdata.nix
> +
```suggestion
```

2024-10-01 06:55 UTC, Enzime commented on modules/services/monitoring/netdata.nix
> +}
```suggestion
}

```

Can you add a trailing newline at the end of the file?

2024-10-02 16:00 UTC, rsrohitsingh682 commented
@Enzime I have resolved the comments. Please let me know if anymore changes are required.

2024-10-03 04:24 UTC, Enzime requested changes
Can you add a test for these changes and squash the changes after that?

2024-10-03 18:41 UTC, rsrohitsingh682 commented
> Can you add a test for these changes and squash the changes after that?

@Enzime This is done.

2024-10-03 23:44 UTC, Enzime approved these changes
LGTM

Thanks for the contribution

2024-10-03 23:44 UTC, merged