jankyborders service option order above or below
LnL7/nix-darwin pull request #1095
Opened 2024-09-29 23:35 UTC by aspauldingcode

Adds undocumented JankyBorders option `order` which can be set to `above` or `below`. Defaults to `below` because it causes issues for some users (hence the reason for not being documented). Helpful for covering the window frame on macos.

2024-10-01 06:48 UTC, Enzime commented
Can you squash the commits into one commit?

2024-10-01 23:51 UTC, aspauldingcode commented
> Can you squash the commits into one commit?

There, I think I did it with [`af95f7b` (#1095)](https://github.com/LnL7/nix-darwin/pull/1095/commits/af95f7b7ec80811cd5662d6b08b45f0160c85d1d)

2024-10-02 01:03 UTC, Enzime commented
Can you also update the jankyborders test?

2024-10-02 01:05 UTC, Enzime requested changes

2024-10-02 01:05 UTC, Enzime commented on modules/services/jankyborders/default.nix
> +      type = types.str;
```suggestion
      type = types.enum [ "above" "below" ];
```

2024-10-02 16:56 UTC, aspauldingcode commented
Hm okay I think I did it. 

> update the jankyborders test

2024-10-03 02:30 UTC, Enzime commented
Did you forget to push the changes for the tests? I don't see any new changes

2024-10-03 14:02 UTC, aspauldingcode commented
> forget to push

Yes.. no.. yes.. maybe. oops.

I think I did this correctly?

2024-10-03 23:47 UTC, Enzime approved these changes
LGTM

Thanks for the contribution

2024-10-03 23:48 UTC, merged

2024-10-04 01:55 UTC, aspauldingcode commented
Hooray, my very first pull request (to any project, ever in my life) being merged. I will remember this moment!