Updated defaults
LnL7/nix-darwin pull request #1107
Opened 2024-10-17 22:35 UTC by Craz1k0ek

* Added some more defaults settings

2024-11-05 02:22 UTC, Enzime requested changes
Can you update the tests?

2024-11-05 05:12 UTC, Samasaur1 commented on modules/system/defaults/finder.nix
> +        Remove items in the bin after 30 days.
Should the docs call it the trash instead of the bin?

2024-11-05 08:33 UTC, Craz1k0ek commented
> Can you update the tests?

@Enzime Not sure what I need to update to make the test succeed. Error message is incomprehensible to me

2024-11-05 08:36 UTC, Enzime commented
Can you rebase your PR on master? It should fix the failing test, and then can you add some more tests to test the new options you added?

2024-11-05 13:55 UTC, Craz1k0ek commented
@Enzime not sure why the tests are failing. Anything wrong in my syntax? The error message is so poor, I can't make anything of it

2024-11-12 15:14 UTC, Enzime commented
This has been superseded by #1163

2024-11-12 15:14 UTC, closed without merging