Use `sysadminctl` instead of `dscl`
LnL7/nix-darwin pull request #1108
Opened 2024-10-19 05:18 UTC by Enzime

Extracted from #1017

This should be PR should be a no-op

2024-10-19 05:21 UTC, Enzime commented on modules/users/default.nix
> +            sysadminctl -deleteUser '${name}' 2> /dev/null
```suggestion
            sysadminctl -deleteUser '${name}'
```

Need to check if the `2> /dev/null` is still necessary

2024-10-19 13:24 UTC, Enzime commented on modules/users/default.nix
> +            sysadminctl -deleteUser '${name}' 2> /dev/null
I'll keep it as `sysadminctl` outputs a lot of unnecessary stuff to stderr

2024-10-21 05:59 UTC, Enzime commented
@emilazy this is ready to review, the current test failure is unrelated

2024-10-21 14:17 UTC, emilazy requested changes
Broadly LGTM, thanks! I haven’t tested adding and deleting users with this yet, so one of us probably should before merging if you haven’t already. Some nits.

2024-10-21 23:46 UTC, Enzime commented on modules/users/default.nix
> +            sysadminctl -deleteUser '${v.name}' 2>/dev/null
Done 👍

2024-10-21 23:46 UTC, Enzime commented on modules/users/default.nix
> +              -shell ${lib.escapeShellArg (shellPath v.shell)}
Done 👍

2024-10-21 23:46 UTC, Enzime commented on modules/users/default.nix
> +            sysadminctl -deleteUser '${name}' 2> /dev/null
Done 👍

2024-10-21 23:47 UTC, Enzime commented on modules/users/default.nix
> +              -shell ${lib.escapeShellArg (shellPath v.shell)}
Done 👍

2024-10-21 23:47 UTC, Enzime commented on modules/users/group.nix
> +  options = with lib; {
Done 👍

2024-10-21 23:48 UTC, Enzime commented on tests/users-groups.nix
> +    grep -zoP "sysadminctl -addUser 'foo' (.|\n)* -UID 42000 (.|\n)* -GID 42000 (.|\n)* -fullName 'Foo user' (.|\n)* -home '/Users/foo' (.|\n)* -shell ${lib.escapeShellArg "/run/current-system/sw/bin
It was previously skipping the backslash and newline however I've replaced the run-on command with `lib.escapeShellArgs` so `(.|\n)*` is no longer necessary

2024-10-21 23:49 UTC, Enzime commented on tests/users-groups.nix
> +    set -v
I left this in as the test otherwise doesn't output very much and is quite cryptic on failure

2024-10-22 14:16 UTC, Enzime commented
@emilazy I've tested this now and it looks like it's working, it should be a relatively safe change as it's still all behind `users.knownUsers` and `users.knownGroups`

2024-10-23 08:13 UTC, emilazy approved these changes
LGTM, will let you decide whether to merge as‐is or apply @isabelroses’ suggestions.

2024-10-23 14:33 UTC, Enzime commented on modules/users/default.nix
> +      ${concatMapStringsSep "\n" (v: let
I appreciate the suggestion but in the end it'll require calling `map` as well, from what I can tell the main benefit of `concatLines` is that it ensures a trailing newline which doesn't make a lot of difference here, so I'm choosing to leave it as is

2024-10-23 14:33 UTC, merged