Feature/controlcenter
LnL7/nix-darwin pull request #1163
Opened 2024-11-10 23:54 UTC by LucasMendesl

Adding support to control center API

2024-11-11 00:02 UTC, Enzime requested changes

2024-11-11 00:02 UTC, Enzime commented on modules/system/defaults/controlcenter.nix
> +        type = types.nullOr (types.enum [ 18 24 ]);
```suggestion
        type = types.nullOr types.bool;
        apply = v: if v == null then null else if v == true then 18 else 24;
```

2024-11-11 00:26 UTC, LucasMendesl commented on modules/system/defaults-write.nix
> +  controlcenter = defaultsToList "${builtins.getEnv "HOME"}/Library/Preferences/ByHost/com.apple.controlcenter" cfg.controlcenter;
using the complete path of this domain is one approach to change this setting, another approach is using the flag `-currentHost` like:

```sh
defaults -currentHost write com.apple.controlcenter BatteryShowPercentage -bool true
```

2024-11-11 00:27 UTC, LucasMendesl commented on modules/system/defaults/controlcenter.nix
> +with lib;
Changed

2024-11-11 00:27 UTC, LucasMendesl commented on modules/system/defaults/controlcenter.nix
> +    system.defaults.controlcenter.BatteryShowPercentage = mkOption {
Changed

2024-11-11 00:28 UTC, LucasMendesl commented on modules/system/defaults/controlcenter.nix
> +        type = types.nullOr (types.enum [ 18 24 ]);
Changed

2024-11-11 00:50 UTC, Enzime commented
You'll need to add your new module file to `modules/module-list.nix`

2024-11-11 00:54 UTC, Enzime commented
You'll also need to add `controlcenter` to here: https://github.com/LnL7/nix-darwin/pull/1163/files#diff-b44750cda15d1291f935ca5053d5aa14c6b1492c38c8bd9c078a0b2d752eaad6L72

And you'll need to update `tests/fixtures/system-defaults-write/activate-user.txt`

2024-11-12 01:27 UTC, LucasMendesl commented
@Enzime, fixed issues and including #1107

2024-11-12 01:58 UTC, LucasMendesl commented
> You'll need to add your new module file to `modules/module-list.nix`

Done

2024-11-12 05:28 UTC, Enzime commented
Can you squash it into 2 commits? One for the `controlcenter` changes and another one for the non-`controlcenter` changes

2024-11-12 09:49 UTC, LucasMendesl commented
> Can you squash it into 2 commits? One for the `controlcenter` changes and another one for the non-`controlcenter` changes

@Enzime, Done 😄

2024-11-12 15:12 UTC, LucasMendesl commented on modules/system/defaults-write.nix
> +        controlcenter
Done

2024-11-12 15:13 UTC, Enzime approved these changes
LGTM

Thanks for the contribution

2024-11-12 15:13 UTC, merged