fix: allow users to disable the homebrew check
LnL7/nix-darwin pull request #1178
Opened 2024-11-17 14:28 UTC by isabelroses

With the recent addition of https://github.com/LnL7/nix-darwin/pull/961, this unintentionally broke [nix-homebrew](https://github.com/zhaofengli/nix-homebrew) see [the issue](https://github.com/zhaofengli/nix-homebrew/issues/45). Thus this PR implments `system.checks.verifyHomebrewInstall` as a way to disable the check allowing nix-homebrew to function normally if users disable it.

2024-11-17 14:31 UTC, emilazy commented
Does `${config.homebrew.brewPrefix}/brew` not exist with nix-homebrew? We should probably fix the check or nix-homebrew if so.

2024-11-17 14:41 UTC, isabelroses commented
> Does `${config.homebrew.brewPrefix}/brew` not exist with nix-homebrew?

It should exist, however the issue is with first activation since it installs homebrew during an activation script so it cannot find homebrew. All following rebuilds behave normally.

2024-11-17 14:44 UTC, ghostiam commented
Doesn't exist, because brew installation fails due to the current check.
If set `homebrew.enable = false;` first, then brew will install using `nix-homebrew` and then everything will work. 
But on a clean system, the new check blocks installation with `homebrew.enable = true;`

2024-11-18 00:02 UTC, Enzime commented
Instead of adding an option to disable the check, what about adding to `nix-homebrew`:

```nix
{
  system.checks.text = mkBefore ''
    INSTALLING_HOMEBREW=1
  '';
}
```

Then we could modify the check in `nix-darwin` to see if that variable is set

2024-11-18 13:24 UTC, isabelroses commented
> Instead of adding an option to disable the check, what about adding to `nix-homebrew`:
> 
> ```nix
> {
>   system.checks.text = mkBefore ''
>     INSTALLING_HOMEBREW=1
>   '';
> }
> ```
> 
> Then we could modify the check in `nix-darwin` to see if that variable is set

I wasn't 100% sure what you ment so I hope [`2792516`](https://github.com/LnL7/nix-darwin/pull/1178/commits/27925163d403e163e7a29c0420a710ac5bd2f43b) is fine

2024-11-19 01:16 UTC, Enzime requested changes

2024-11-19 01:16 UTC, Enzime commented on modules/system/checks.nix
> +    if [[ ! -f ${escapeShellArg config.homebrew.brewPrefix}/brew && -z "$INSTALLING_HOMEBREW" ]]; then
```suggestion
    if [[ ! -f ${escapeShellArg config.homebrew.brewPrefix}/brew && -z "${INSTALLING_HOMEBREW:-}" ]]; then
```

2024-11-19 10:07 UTC, Enzime approved these changes
LGTM

Thanks for the contribution

2024-11-19 10:09 UTC, Enzime requested changes

2024-11-19 10:09 UTC, Enzime commented on modules/system/checks.nix
> +    if [[ ! -f ${escapeShellArg config.homebrew.brewPrefix}/brew && -z "${INSTALLING_HOMEBREW:-}" ]]; then
```suggestion
    if [[ ! -f ${escapeShellArg config.homebrew.brewPrefix}/brew && -z "''${INSTALLING_HOMEBREW:-}" ]]; then
```

2024-11-19 11:42 UTC, Enzime approved these changes

2024-11-19 11:42 UTC, merged