Petition to add apple watch authentication to `sudo` command
LnL7/nix-darwin pull request #1216
Opened 2024-12-05 06:27 UTC by Coosis

With projects like [pam-watchid](https://github.com/Logicer16/pam-watchid), it's now possible to enable apple watches to authenticate `sudo` commands, alongside with `TouchID`. This is mostly a raw idea, but I would love to see something like this in `nix-darwin`.

Because this is used to present an idea, there are couple things to note:
1. I did not add any tests
2. I straight up embedded a package in the source code
3. The `x86` part fails to compile for some reason so that's now commented out so I'll need some help with that

I would love for others to pick this up as this is my first time contributing to the project, and I am unfamiliar with:
1. How to use apple's toolchains when building packages
2. Which packages should I include
3. The best practices

2024-12-05 07:26 UTC, Enzime commented
The package should live in Nixpkgs not in nix-darwin

Also, I don’t think `pam-watchid` is necessary. I have `pam_tid` enabled through `security.pam.enableSudoTouchIdAuth` and I went into `System Settings` and allowed my Apple Watch to unlock my laptop and every time I’m prompted for my fingerprint for `sudo` it also asks on my Apple Watch

2024-12-05 07:42 UTC, Coosis commented
> The package should live in Nixpkgs not in nix-darwin
> 
> Also, I don’t think `pam-watchid` is necessary. I have `pam_tid` enabled through `security.pam.enableSudoTouchIdAuth` and I went into `System Settings` and allowed my Apple Watch to unlock my laptop and every time I’m prompted for my fingerprint for `sudo` it also asks on my Apple Watch

Simply adding it to Nixpkgs will not put the .pam file in place. For some reason my machine doesn't let me use my watch when `security.pam.enableSudoTouchIdAuth` is enabled, I believe this happens to machines that doesn't have a touchid(also laptops that have lids closed).

2024-12-05 07:44 UTC, Enzime commented
First you’ll need to add the package to Nixpkgs, then you can use it through `pkgs` from a nix-darwin module

2024-12-05 12:37 UTC, bestlem commented
@Enzime - I think that pam-watchid is needed if you only have an Apple Watch and no TouchId. So not needed on a laptop but it is needed on a desktop without an Apple TouchId keyboard.

2024-12-05 23:52 UTC, Enzime commented
Have you enabled your Apple Watch to unlock your applications and your Mac in System Settings? It's under `Login Password` on non-Touch ID devices

2024-12-06 04:20 UTC, Coosis commented
> Have you enabled your Apple Watch to unlock your applications and your Mac in System Settings? It's under `Login Password` on non-Touch ID devices

Yes, I have. No pop up to use apple watch.

2024-12-15 22:39 UTC, Samasaur1 commented
There was a discussion on Matrix about this and we're waiting on https://github.com/Logicer16/pam-watchid/pull/5 before adding that repo to nixpkgs which will then allow this PR to progress.

It hasn't been that long since I opened that PR, but if it really drags on for a while I might just add my fork to nixpkgs instead and then this PR will be able to move forwards

2024-12-15 22:41 UTC, Samasaur1 commented
This also probably depends on #1205 for linking the built `.so` file into `/usr/local/lib/pam`

2024-12-15 22:41 UTC, Samasaur1 commented
cc: @Coosis to confirm, but iirc we confirmed on Matrix that it works to symlink the `.so` file into place and we don't have to copy it

2024-12-15 23:43 UTC, Enzime commented
> This also probably depends on #1205 for linking the built `.so` file into `/usr/local/lib/pam`

PAM libraries can be used directly from the Nix Store I believe

2024-12-15 23:57 UTC, Coosis commented
> cc: @Coosis to confirm, but iirc we confirmed on Matrix that it works to symlink the `.so` file into place and we don't have to copy it

Yes symlink will work just fine. Still waiting for #1205 and I definitely think you should just fork it and add fork to nixpkgs.

2024-12-16 00:02 UTC, Enzime commented
You can just make a PR to nixpkgs and use your pull request as a patch on top of their repo

2024-12-16 06:58 UTC, Samasaur1 commented
> PAM libraries can be used directly from the Nix Store I believe

oh great, even easier! (i have no experience with PAM stuff, just the Swift side)

> You can just make a PR to nixpkgs and use your pull request as a patch on top of their repo

Mostly I'm just wondering if the repo is being supported at all — it seems like it's a fork of a fork of a fork and I'm wondering if any in the chain are maintained or if they were made to fix one thing and then essentially abandoned. If so, I may just point the nixpkgs package to my repository so I can maintain it more easily

2024-12-25 01:08 UTC, Logicer16 commented
> I'm wondering if any in the chain are maintained

For the record, I intend to maintain my fork for the foreseeable future.

2024-12-25 01:20 UTC, Samasaur1 commented
Okay, yay! I'll open a PR to nixpkgs when I get a chance and link it here

2024-12-25 06:39 UTC, Samasaur1 commented
https://github.com/NixOS/nixpkgs/pull/368071

2024-12-31 16:48 UTC, tymscar commented
Now that nixpkgs has merged @Samasaur1's PR, this should go fairly well, right?

2024-12-31 16:57 UTC, Samasaur1 commented
Depends on whether the library can be used directly from the Nix store or whether it needs to be linked into place. If it can be used directly, then there's no blockers. If it needs to be linked, we're waiting on #1205.

2024-12-31 17:23 UTC, Coosis commented
> Depends on whether the library can be used directly from the Nix store or whether it needs to be linked into place. If it can be used directly, then there's no blockers. If it needs to be linked, we're waiting on #1205.

I actually don't know how a pam module can be used from nix store directly.

2025-01-01 01:37 UTC, Samasaur1 commented
> > Depends on whether the library can be used directly from the Nix store or whether it needs to be linked into place. If it can be used directly, then there's no blockers. If it needs to be linked, we're waiting on #1205.
> 
> I actually don't know how a pam module can be used from nix store directly.

My guess is that you'd put the full path to the `.so` file in one of the files under `/etc/pam.d`? but again I haven't messed around with PAM at all

2025-02-07 19:43 UTC, Coosis commented
> I was able to use the pam module directly from the store:
> 
> ```nix
>   etc = {
>     "pam.d/sudo_local".text = ''
>       auth sufficient pam_tid.so
>       auth sufficient ${pkgs.pam-watchid}/lib/pam_watchid.so
>     '';
>   };
> ```

Nice! I would say this could be the closest thing possible. But i do think this could override other pam modules if handled incorrectly. My laziness is kicking in and telling me to take this and call it a day

2025-02-07 21:12 UTC, tymscar commented
Would this need to be added manually?

2025-02-08 08:35 UTC, Samasaur1 commented
At the moment, yes, you'll need to do it manually

2025-02-25 03:11 UTC, Enzime commented
Now that #1344 is merged, you can rebase this PR and add an option similar to `security.pam.services.sudo_local.reattach`

2025-02-25 12:27 UTC, Enzime commented
It seems the PR got closed, if that wasn't your intention, you'll need to push some new commits to this branch before you can reopen the branch

2025-02-25 12:48 UTC, Enzime commented
Yeah, it should be fine to keep using your `master` branch. GitHub ties the pull request to the branch so if you want to switch branches you’ll need to make a new PR but it would probably be best to keep using this PR

2025-02-25 15:42 UTC, Enzime requested changes
After you make your changes, can you squash the changes into one commit and change the description to:

```
pam: add `pam_watchid` support
```

2025-02-25 15:53 UTC, Coosis commented on modules/security/pam.nix
> +			watchIdAuth = lib.mkEnableOption "" // {
Sorry about that. Is this better?

2025-02-27 06:09 UTC, Enzime approved these changes
LGTM

Thanks for the contribution

2025-02-27 06:09 UTC, merged