Add DeterminateSystems installer 0.32.2 support
LnL7/nix-darwin pull request #1234
Opened 2024-12-22 00:50 UTC by x13-me

Add DeterminateSystems Nix installer `0.32.2` to known hashes

2024-12-22 01:00 UTC, Enzime requested changes
Can you add a copy of the file to `docs/known-files`?

2025-01-08 18:47 UTC, emilazy commented
@x13-me Friendly ping :) The commit message should also look like `nix: add Determinate Systems Nix installer 0.32.2 to known hashes`.

Would you like someone else to take this PR over?

2025-01-08 23:23 UTC, x13-me commented
> @x13-me Friendly ping :) The commit message should also look like `nix: add Determinate Systems Nix installer 0.32.2 to known hashes`.
> 
> 
> 
> Would you like someone else to take this PR over?

Please hand to someone else; personal life has pulled me away

2025-01-12 15:16 UTC, x13-me commented
> Can you add a copy of the file to `docs/known-files`?

I've uploaded the file as a [gist](https://gist.github.com/x13-me/ef53cfa6ebf8e9f37db43dd08c9a25f7), because github won't allow me to attach a `.conf` to a comment, I believe this preserves the file hash, it is as-installed on my system, no modifications

2025-01-14 16:09 UTC, x13-me commented
> It looks like that’s the hash from an activated `nix-darwin` configuration. When installing with v0.32.2 locally I seem to get a configuration matching a hash we already have and it activates without issue. Are you perhaps trying to reinstall nix-darwin after having already installed it?

Not as far as I'm aware, this was a complete fresh install, no doubt I've done something wrong though

2025-01-14 22:35 UTC, Enzime commented
When I hash the file you linked, it gives a different hash to the hash you added in this PR:

```
$ curl https://gist.githubusercontent.com/x13-me/ef53cfa6ebf8e9f37db43dd08c9a25f7/raw/9eb2c1c05c0f038310a93d9959c981d3ac459c9f/kyf3mhhn565qhc2rzfaglig39m7yij1r-nix.conf | shasum -a 256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   518  100   518    0     0   1242      0 --:--:-- --:--:-- --:--:--  1245
7ac9c0f815d09e16449c9733e5a2bcf2ddf925f938a3b4eb1267e1eb0ded4b66  -
```

This should work correctly as the other files in `doc/known-files` work:

```
$ curl https://raw.githubusercontent.com/LnL7/nix-darwin/refs/heads/master/doc/known-files/0235d3c1b6cf21e7043fbc98e239ee4bc648048aafaf6be1a94a576300584ef2 | shasum -a 256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   255  100   255    0     0    528      0 --:--:-- --:--:-- --:--:--   529
0235d3c1b6cf21e7043fbc98e239ee4bc648048aafaf6be1a94a576300584ef2  -
```

2025-01-27 15:11 UTC, x13-me commented
> When I hash the file you linked, it gives a different hash to the hash you added in this PR:
> 
> ```
> $ curl https://gist.githubusercontent.com/x13-me/ef53cfa6ebf8e9f37db43dd08c9a25f7/raw/9eb2c1c05c0f038310a93d9959c981d3ac459c9f/kyf3mhhn565qhc2rzfaglig39m7yij1r-nix.conf | shasum -a 256
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   518  100   518    0     0   1242      0 --:--:-- --:--:-- --:--:--  1245
> 7ac9c0f815d09e16449c9733e5a2bcf2ddf925f938a3b4eb1267e1eb0ded4b66  -
> ```
> 
> This should work correctly as the other files in `doc/known-files` work:
> 
> ```
> $ curl https://raw.githubusercontent.com/LnL7/nix-darwin/refs/heads/master/doc/known-files/0235d3c1b6cf21e7043fbc98e239ee4bc648048aafaf6be1a94a576300584ef2 | shasum -a 256
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   255  100   255    0     0    528      0 --:--:-- --:--:-- --:--:--   529
> 0235d3c1b6cf21e7043fbc98e239ee4bc648048aafaf6be1a94a576300584ef2  -
> ```

I am uncertain as to why this is happening, I'll have to wipe my system and try again

2025-01-27 15:11 UTC, closed without merging