feat: add screencapture.target option
LnL7/nix-darwin pull request #1242
Opened 2024-12-28 22:53 UTC by filipkania

Adds the ability to set `com.apple.screencapture.target` default, which tells screencapture to output screenshot to e.g. clipboard. I prefer to put my screenshots directly into my clipboard, and there wasn't an option to do that through nix-darwin, so i've made the PR :)

Tested it using different valid values on Sequoia, valid values were observed by setting different "Save to" settings and reading using `defaults read com.apple.screencapture target`:

![untitled](https://github.com/user-attachments/assets/0a71bf8c-bd45-44bf-92ce-c864ddb835b6)

2024-12-28 23:02 UTC, Enzime commented
Can you update the tests?

2024-12-28 23:15 UTC, filipkania commented
sure!

2024-12-29 08:11 UTC, Enzime requested changes

2024-12-29 08:11 UTC, Enzime commented on modules/system/defaults/screencapture.nix
> +      type = types.nullOr types.str;
```suggestion
      type = types.nullOr (types.enum [ "file" "clipboard" ... ]);
```

2024-12-29 11:07 UTC, Enzime reviewed
LGTM

Thanks for the contribution

2024-12-29 11:08 UTC, Enzime approved these changes

2024-12-29 11:08 UTC, merged