Don't run static bashrc only for pure nix-shell
LnL7/nix-darwin pull request #163
Opened 2019-09-15 18:46 UTC by kubek2k

2019-09-19 20:09 UTC, LnL7 commented
This was added as a workaround in the first place, do you have any idea why this doesn't seem necessary on linux?

2019-09-21 20:44 UTC, kubek2k commented
> This was added as a workaround in the first place, do you have any idea why this doesn't seem necessary on linux?

I have no idea - since I don't use NixOS (or nix on any other linux). Maybe it could be a versioning issue (bash v2.7 on mac as default, as oppposed to v4 everywhere else?)

2019-11-01 10:31 UTC, kubek2k commented
@LnL7 the nix-shell man states that the `IN_NIX_SHELL` started to be set since nix 2.0. Maybe that was the cause?

2022-12-29 09:20 UTC, hagl commented
Is there a chance to get this PR merged? 
I use `programs.bash.interactiveShellInit` in my `darwin-configuration.nix` to setup a shell prompt containing the git branch, but that doesn't work in `nix-shell`s because of this early return.

2023-07-26 03:03 UTC, Enzime requested changes
Thanks for the contribution, can you rebase your PR?

2023-07-26 03:03 UTC, Enzime commented on modules/programs/bash/default.nix
> +      if [ "$IN_NIX_SHELL" == "pure" ]; then return; fi
```suggestion
      if [ "$IN_NIX_SHELL" = "pure" ]; then return; fi
```

2023-07-26 06:59 UTC, Enzime commented
@kubek2k can you rebase the PR? I can't merge until all the tests have succeeded

2023-07-26 10:45 UTC, Enzime approved these changes
LGTM

2023-07-26 10:45 UTC, merged