Fix unbound variable `etcProblems`
LnL7/nix-darwin pull request #803
Opened 2023-11-09 11:48 UTC by felixscheinost

I have another activationScript which traps errors. Currently `etcProblems` can be unbound.

2023-11-10 15:23 UTC, Enzime requested changes

2023-11-10 15:23 UTC, Enzime commented on modules/system/etc.nix
> +      declare -a etcProblems=()
From my testing this doesn’t fix the problem:

```
$ set -u
$ declare -a etcProblems=()
bash: etcProblems: unbound variable
```

2023-11-10 17:08 UTC, felixscheinost commented
I think the test you did was incorrect. Can you test the following?

```
$ bash -u -c 'declare -a etcProblems; echo "number of problems: ${#etcProblems[@]}"'
bash: line 1: etcProblems: unbound variable

$ bash -u -c 'declare -a etcProblems=(); echo "number of problems: ${#etcProblems[@]}"'
number of problems: 0
```

It seems that as `etcProblems` is declared as an array it may only be used as such.

Also I am successfully running this branch, while master doesn't work for me. So it seems to be at least a a step in the right direction 😃

2023-11-13 09:32 UTC, Enzime approved these changes
Thanks for the contribution, LGTM :+1:

2023-11-13 09:32 UTC, merged

2023-11-13 12:10 UTC, felixscheinost commented
Cool, thanks!