Add `nix.linux-builder.systems` option to set corresponding `nix.buildMachines.*.systems` option
LnL7/nix-darwin pull request #816
Opened 2023-11-22 23:17 UTC by ethnt

I've set up my local `linux-builder` to emulate `x86_64-linux` as well as `aarch64-linux` (jury's out as to how well that will work), but I still need to be able to set that option in `/etc/nix/machines`. I've added an option for this in `nix.linux-builder`. Potentially in the future it would be a better idea to simply allow `extraBuilderConfig` or something similar, but I stuck with convention in this PR.

2023-11-22 23:21 UTC, Enzime requested changes
I think it makes more sense to specify the default `system` as part of the new `systems` option

2023-11-22 23:21 UTC, Enzime commented on modules/nix/linux-builder.nix
> +      systems = [ "${stdenv.hostPlatform.uname.processor}-linux" ] ++ cfg.systems;
```suggestion
      inherit (cfg) systems;
```

2023-11-22 23:22 UTC, Enzime requested changes

2023-11-22 23:22 UTC, Enzime commented on modules/nix/linux-builder.nix
> +      default = [ ];
```suggestion
      default = [ "${stdenv.hostPlatform.uname.processor}-linux" ];
```

2023-11-22 23:22 UTC, Enzime commented on modules/nix/linux-builder.nix
> +      description = ''
```suggestion
      description = lib.mdDoc ''
```

2023-11-23 01:40 UTC, ethnt commented
@Enzime Thanks for the review, I've made those changes!

2023-11-23 03:24 UTC, Enzime requested changes

2023-11-23 03:24 UTC, Enzime commented on modules/nix/linux-builder.nix
> +      default = [ "${stdenv.hostPlatform.uname.processor}-linux" ];
```suggestion
      default = [ "${stdenv.hostPlatform.uname.processor}-linux" ];
      defaultText = literalExpression ''[ "''${stdenv.hostPlatform.uname.processor}-linux" ]'';
```

2024-02-23 02:31 UTC, merged