darwin-rebuild: fix sudo invocation on High Sierra
LnL7/nix-darwin pull request #831
Opened 2023-12-15 13:58 UTC by rkitover

The version of sudo on macOS 10.13 High Sierra does not support the `--preserve-env=LIST` option syntax.

Override sudo with a shell function that checks for the availability of this option syntax, and use just `--preserve-env` otherwise.

2023-12-17 11:39 UTC, Enzime requested changes

2023-12-17 11:39 UTC, Enzime commented on pkgs/nix-tools/darwin-rebuild.sh
> +    command sudo -H --preserve-env "$@"
```suggestion
    command sudo -H "$@"
```

If we can't preserve just `$PATH`, I reckon it should be fine to just preserve `$HOME`

2023-12-17 13:14 UTC, rkitover commented
How's this?

2023-12-22 00:44 UTC, Enzime requested changes

2023-12-22 00:44 UTC, Enzime commented on pkgs/nix-tools/darwin-rebuild.sh
> +    command sudo -H -- sh -c 'PATH='"'$PATH'"' "$@"' -- "$@"
Not a big fan of how brittle that command looks, I would personally much rather not have `$PATH` passed, as it was only implemented for #798 and I'd consider it if more people ran into the same issue

```suggestion
    command sudo -H "$@"
```

2023-12-22 00:47 UTC, Enzime commented on pkgs/nix-tools/darwin-rebuild.sh
> +    command sudo -H --preserve-env=PATH "$@"
```suggestion
    command sudo -H --preserve-env=PATH env "$@"
```

As the `env` command was added to ensure that the preserved `PATH` gets searched for the binary, I think it'd be better to move it here

2023-12-22 00:47 UTC, Enzime commented on pkgs/nix-tools/darwin-rebuild.sh
> +    sudo env nix-env -p "$profile" "${extraProfileFlags[@]}"
```suggestion
    sudo nix-env -p "$profile" "${extraProfileFlags[@]}"
```

2023-12-22 00:47 UTC, Enzime commented on pkgs/nix-tools/darwin-rebuild.sh
> +    sudo env nix-env -p "$profile" --set "$systemConfig"
```suggestion
    sudo nix-env -p "$profile" --set "$systemConfig"
```

2023-12-22 14:44 UTC, rkitover commented
Updated.

2023-12-22 18:53 UTC, Enzime approved these changes
Thanks for the contribution

LGTM

2023-12-22 18:53 UTC, merged