Expose extendModules attr
LnL7/nix-darwin pull request #920
Opened 2024-03-30 10:28 UTC by hiroqn

expose extendModules

implementation reference is https://github.com/nix-community/home-manager/blob/3142bdcc470e1e291e1fbe942fd69e06bd00c5df/modules/default.nix#L43

ref: https://github.com/LnL7/nix-darwin/pull/777
ref: https://github.com/LnL7/nix-darwin/issues/609

2024-10-21 23:34 UTC, remi-gelinas commented
@LnL7 Any chance this could get a pair of eyes? I need `extendModules` to be passed through for a composite use case I have, and I figured I'd see if anyone tried before raising a PR myself.

2025-03-13 07:19 UTC, Enzime requested changes

2025-03-13 07:19 UTC, Enzime commented on eval-config.nix
> +  withExtraAttrs = module:
Can you rename `module` to `configuration` and merge this set with `configuration` to match NixOS's implementation:

https://github.com/NixOS/nixpkgs/blob/b1f2198021490b51fb92b8b09db97b9ba2a7b4ce/nixos/lib/eval-config.nix

2025-03-25 02:13 UTC, hiroqn commented on eval-config.nix
> +  withExtraAttrs = module:
Thanks for your feedback @Enzime !
I fixed it to match NixOS's implementation. But another attributes(`_type`, `class`, `type`) is exposed, is this ok? or should I remove them?
NixOS configuration (`nixpkgs.lib.nixosSystem`) already expose these attributes.

2025-03-25 02:23 UTC, Enzime approved these changes
LGTM

Thanks for the contribution

2025-03-25 02:27 UTC, merged