Add persistent others to dock
LnL7/nix-darwin pull request #928
Opened 2024-04-08 13:11 UTC by rmgpinto

Add persistent others to dock. Closes https://github.com/LnL7/nix-darwin/issues/927.

2024-04-08 13:12 UTC, rmgpinto commented
@Enzime @Samasaur1

2024-04-09 22:20 UTC, Samasaur1 requested changes
The actual change here looks good to me, but I'd like it if you could avoid making unrelated formatting-only changes in the same PR

2024-04-10 07:22 UTC, rmgpinto commented
@Samasaur1  I didn't notice, it's my linter and auto format on save. I've reverted the formatting changes.

2024-05-10 15:26 UTC, rmgpinto commented
@Samasaur1 I can't seem to understand why the tests fail. Are you able to help?

2024-05-11 04:31 UTC, Samasaur1 commented
Okay I manually checked the failing test on unstable, and it's only failing because of a missing newline. Seems like a false alarm; let me take a closer look and determine whether it's better to change the test or change the implementation back

2024-05-11 04:33 UTC, Samasaur1 commented
Ah, okay, you need another newline in the test file

2024-05-11 04:38 UTC, Samasaur1 requested changes

2024-05-11 04:38 UTC, Samasaur1 commented on tests/fixtures/system-defaults-write/activate-user.txt
```suggestion


```

2024-05-12 21:33 UTC, rmgpinto commented
Thanks @Samasaur1, tests passed.

2024-05-13 00:20 UTC, Enzime commented
Can you rebase the PR?

2024-05-13 06:18 UTC, rmgpinto commented
done @Enzime

2024-05-13 12:14 UTC, Enzime commented
Can you rebase your PR on top of the latest master and squash your commits? Ideally your branch shouldn't contain the `fmt` commits and should only contain your commits

2024-05-13 12:47 UTC, rmgpinto commented
should be ok now @Enzime

2024-05-13 16:26 UTC, rmgpinto commented
The tests seem to be flaky, sometimes that check passes, others it doesn't.

2024-05-14 02:22 UTC, Enzime approved these changes
LGTM

Thanks for the contribution

2024-05-14 02:22 UTC, merged

2024-05-14 22:20 UTC, thegleich commented
This introduces a regression (warning) by using `lib.mdDoc`

`mdDoc` usage has been been removed in https://github.com/LnL7/nix-darwin/pull/932

2024-05-15 06:59 UTC, rmgpinto commented
Fixing in https://github.com/LnL7/nix-darwin/pull/950