checks.nix: disable verifyBuildUsers for auto-allocate-uids
LnL7/nix-darwin pull request #978
Opened 2024-06-19 06:33 UTC by usertam

Follow https://github.com/LnL7/nix-darwin/pull/681, but disable the check automatically if `config.nix.settings.auto-allocate-uids` is explicitly set to `true`.

Note that by default `config.nix.settings = {}`, and this should not affact people who do not configure `nix.settings.auto-allocate-uids`.

2024-06-19 14:05 UTC, emilazy requested changes
Sure, seems like a good idea to me. I must disclaim that this setting is known to break a bunch of builds so you might not enjoy having it on, but we might as well not gratuitously break it further.

2024-06-19 14:05 UTC, emilazy commented on modules/system/checks.nix
> +      default = !(hasAttr "auto-allocate-uids" config.nix.settings && config.nix.settings.auto-allocate-uids);
Nit: `!(config.nix.settings.auto-allocate-uids or false)`.

2024-06-23 07:15 UTC, usertam commented on modules/system/checks.nix
> +      default = !(hasAttr "auto-allocate-uids" config.nix.settings && config.nix.settings.auto-allocate-uids);
Thanks!

2024-06-23 07:37 UTC, emilazy approved these changes
Thanks! I hope this can be the default one day, if we ever figure out how to deal with builds that want to know about their current user.

2024-06-23 07:37 UTC, merged