Add `User` and  already generated `IdentityFile` to ssh_config for `nix.linux-builder`
LnL7/nix-darwin pull request #997
Opened 2024-07-09 20:17 UTC by thanegill

2024-07-10 01:32 UTC, Enzime requested changes

2024-07-10 01:32 UTC, Enzime commented on modules/nix/linux-builder.nix
> +        IdentityFile ${cfg.workingDirectory}/keys/builder_ed25519
```suggestion
        IdentityFile /etc/nix/builder_ed25519
```

2024-07-13 03:46 UTC, Enzime approved these changes
LGTM

2024-07-13 03:47 UTC, Enzime commented
Just wondering, what prompted you to make these changes?

2024-07-15 18:19 UTC, thanegill commented
> Just wondering, what prompted you to make these changes?

I have a local nix-cache that I wanted the builder to use. SSH was needed this to debug the connection, found out that the issue was the by default DNS on the linux-builder is [hard-coded to `8.8.8.8`](https://github.com/NixOS/nixpkgs/blob/be6ca51c35ce13ea1b8365aa95946f3643b58db2/nixos/modules/profiles/macos-builder.nix#L104).

2024-07-15 23:34 UTC, merged

2024-07-16 10:49 UTC, Montmorency commented
I ran into similar [issue](https://github.com/LnL7/nix-darwin/issues/913) and manually configured the ssh alias to get it working. Thanks for putting this in upstream 👍